name: Download blob from Azure Blob Storage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
         
jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - uses: fixpoint/azblob-download-artifact@v3
      with:
        connection-string: ${{ secrets.AZURE_CONNECTIONSTRING }}
        name: test1.json
        container: container1
    - name: view file contents 
      run: cat test1.json
  
